# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rufirst', '0005_auto_20170627_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=420, null=True),
        ),
    ]
