# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rufirst', '0006_auto_20170627_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user-photos'),
        ),
    ]
