# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rufirst', '0009_auto_20170628_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='/Users/zhaoyu/PycharmProjects/RuDjango/rufirst/static/default.jpg', null=True, upload_to='userphotos'),
        ),
    ]
